// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhcibpfhiqgtzvyhlegj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoY2licGZoaXFndHp2eWhsZWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NDg3MzUsImV4cCI6MjA4NDMyNDczNX0.J9woJSdENaHMbuiqjFa24lxX78HVkqbsopLmOrqtWM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});